# 참고자료
# 모두를 위한 머신러닝/딥러닝 강의
# 홍콩과기대 김성훈
# http://hunkim.github.io/ml

import gym

games = [
'Acrobot-v1',
'AirRaid-v3',
'Amidar-v3',
'Assault-v3',
'BeamRider-v3',
'Boxing-v3',
'CrazyClimber-v3',
'DoubleDunk-v3',
'Enduro-v3',
'Freeway-v3',
'Gopher-v0',
'LunarLander-v2',
'Pong-v0',
'Robotank-v3',
'Walker2d-v1',
'YarsRevenge',
'Zaxxon-v3',
'SpaceInvaders-v0',
'Breakout-v0',
'Tennis-v0',
'Solaris-v0',
'Skiing-v0',
'LunarLander-v2']

for game in range(len(games)):
    env = gym.make(games[game])
    env.reset()

    for _ in range(1000):
        env.render()
        _, _, done, _ = env.step(env.action_space.sample())

        if done:
            env.close()
            break

"""
Acrobot-v1
AirRaid-ram-v0
AirRaid-ram-v3
AirRaid-ramDeterministic-v0
AirRaid-ramDeterministic-v3
AirRaid-ramNoFrameskip-v0
AirRaid-ramNoFrameskip-v3
AirRaid-v0
AirRaid-v3
AirRaidDeterministic-v0
AirRaidDeterministic-v3
AirRaidNoFrameskip-v0
AirRaidNoFrameskip-v3
Alien-ram-v0
Alien-ram-v3
Alien-ramDeterministic-v0
Alien-ramDeterministic-v3
Alien-ramNoFrameskip-v0
Alien-ramNoFrameskip-v3
Alien-v0
Alien-v3
AlienDeterministic-v0
AlienDeterministic-v3
AlienNoFrameskip-v0
AlienNoFrameskip-v3
Amidar-ram-v0
Amidar-ram-v3
Amidar-ramDeterministic-v0
Amidar-ramDeterministic-v3
Amidar-ramNoFrameskip-v0
Amidar-ramNoFrameskip-v3
Amidar-v0
Amidar-v3
AmidarDeterministic-v0
AmidarDeterministic-v3
AmidarNoFrameskip-v0
AmidarNoFrameskip-v3
Ant-v1
Assault-ram-v0
Assault-ram-v3
Assault-ramDeterministic-v0
Assault-ramDeterministic-v3
Assault-ramNoFrameskip-v0
Assault-ramNoFrameskip-v3
Assault-v0
Assault-v3
AssaultDeterministic-v0
AssaultDeterministic-v3
AssaultNoFrameskip-v0
AssaultNoFrameskip-v3
Asterix-ram-v0
Asterix-ram-v3
Asterix-ramDeterministic-v0
Asterix-ramDeterministic-v3
Asterix-ramNoFrameskip-v0
Asterix-ramNoFrameskip-v3
Asterix-v0
Asterix-v3
AsterixDeterministic-v0
AsterixDeterministic-v3
AsterixNoFrameskip-v0
AsterixNoFrameskip-v3
Asteroids-ram-v0
Asteroids-ram-v3
Asteroids-ramDeterministic-v0
Asteroids-ramDeterministic-v3
Asteroids-ramNoFrameskip-v0
Asteroids-ramNoFrameskip-v3
Asteroids-v0
Asteroids-v3
AsteroidsDeterministic-v0
AsteroidsDeterministic-v3
AsteroidsNoFrameskip-v0
AsteroidsNoFrameskip-v3
Atlantis-ram-v0
Atlantis-ram-v3
Atlantis-ramDeterministic-v0
Atlantis-ramDeterministic-v3
Atlantis-ramNoFrameskip-v0
Atlantis-ramNoFrameskip-v3
Atlantis-v0
Atlantis-v3
AtlantisDeterministic-v0
AtlantisDeterministic-v3
AtlantisNoFrameskip-v0
AtlantisNoFrameskip-v3
BankHeist-ram-v0
BankHeist-ram-v3
BankHeist-ramDeterministic-v0
BankHeist-ramDeterministic-v3
BankHeist-ramNoFrameskip-v0
BankHeist-ramNoFrameskip-v3
BankHeist-v0
BankHeist-v3
BankHeistDeterministic-v0
BankHeistDeterministic-v3
BankHeistNoFrameskip-v0
BankHeistNoFrameskip-v3
BattleZone-ram-v0
BattleZone-ram-v3
BattleZone-ramDeterministic-v0
BattleZone-ramDeterministic-v3
BattleZone-ramNoFrameskip-v0
BattleZone-ramNoFrameskip-v3
BattleZone-v0
BattleZone-v3
BattleZoneDeterministic-v0
BattleZoneDeterministic-v3
BattleZoneNoFrameskip-v0
BattleZoneNoFrameskip-v3
BeamRider-ram-v0
BeamRider-ram-v3
BeamRider-ramDeterministic-v0
BeamRider-ramDeterministic-v3
BeamRider-ramNoFrameskip-v0
BeamRider-ramNoFrameskip-v3
BeamRider-v0
BeamRider-v3
BeamRiderDeterministic-v0
BeamRiderDeterministic-v3
BeamRiderNoFrameskip-v0
BeamRiderNoFrameskip-v3
Berzerk-ram-v0
Berzerk-ram-v3
Berzerk-ramDeterministic-v0
Berzerk-ramDeterministic-v3
Berzerk-ramNoFrameskip-v0
Berzerk-ramNoFrameskip-v3
Berzerk-v0
Berzerk-v3
BerzerkDeterministic-v0
BerzerkDeterministic-v3
BerzerkNoFrameskip-v0
BerzerkNoFrameskip-v3
BipedalWalker-v2
BipedalWalkerHardcore-v2
Blackjack-v0
Bowling-ram-v0
Bowling-ram-v3
Bowling-ramDeterministic-v0
Bowling-ramDeterministic-v3
Bowling-ramNoFrameskip-v0
Bowling-ramNoFrameskip-v3
Bowling-v0
Bowling-v3
BowlingDeterministic-v0
BowlingDeterministic-v3
BowlingNoFrameskip-v0
BowlingNoFrameskip-v3
Boxing-ram-v0
Boxing-ram-v3
Boxing-ramDeterministic-v0
Boxing-ramDeterministic-v3
Boxing-ramNoFrameskip-v0
Boxing-ramNoFrameskip-v3
Boxing-v0
Boxing-v3
BoxingDeterministic-v0
BoxingDeterministic-v3
BoxingNoFrameskip-v0
BoxingNoFrameskip-v3
Breakout-ram-v0
Breakout-ram-v3
Breakout-ramDeterministic-v0
Breakout-ramDeterministic-v3
Breakout-ramNoFrameskip-v0
Breakout-ramNoFrameskip-v3
Breakout-v0
Breakout-v3
BreakoutDeterministic-v0
BreakoutDeterministic-v3
BreakoutNoFrameskip-v0
BreakoutNoFrameskip-v3
CNNClassifierTraining-v0
CarRacing-v0
Carnival-ram-v0
Carnival-ram-v3
Carnival-ramDeterministic-v0
Carnival-ramDeterministic-v3
Carnival-ramNoFrameskip-v0
Carnival-ramNoFrameskip-v3
Carnival-v0
Carnival-v3
CarnivalDeterministic-v0
CarnivalDeterministic-v3
CarnivalNoFrameskip-v0
CarnivalNoFrameskip-v3
CartPole-v0
CartPole-v1
Centipede-ram-v0
Centipede-ram-v3
Centipede-ramDeterministic-v0
Centipede-ramDeterministic-v3
Centipede-ramNoFrameskip-v0
Centipede-ramNoFrameskip-v3
Centipede-v0
Centipede-v3
CentipedeDeterministic-v0
CentipedeDeterministic-v3
CentipedeNoFrameskip-v0
CentipedeNoFrameskip-v3
ChopperCommand-ram-v0
ChopperCommand-ram-v3
ChopperCommand-ramDeterministic-v0
ChopperCommand-ramDeterministic-v3
ChopperCommand-ramNoFrameskip-v0
ChopperCommand-ramNoFrameskip-v3
ChopperCommand-v0
ChopperCommand-v3
ChopperCommandDeterministic-v0
ChopperCommandDeterministic-v3
ChopperCommandNoFrameskip-v0
ChopperCommandNoFrameskip-v3
ConvergenceControl-v0
Copy-v0
CrazyClimber-ram-v0
CrazyClimber-ram-v3
CrazyClimber-ramDeterministic-v0
CrazyClimber-ramDeterministic-v3
CrazyClimber-ramNoFrameskip-v0
CrazyClimber-ramNoFrameskip-v3
CrazyClimber-v0
CrazyClimber-v3
CrazyClimberDeterministic-v0
CrazyClimberDeterministic-v3
CrazyClimberNoFrameskip-v0
CrazyClimberNoFrameskip-v3
DemonAttack-ram-v0
DemonAttack-ram-v3
DemonAttack-ramDeterministic-v0
DemonAttack-ramDeterministic-v3
DemonAttack-ramNoFrameskip-v0
DemonAttack-ramNoFrameskip-v3
DemonAttack-v0
DemonAttack-v3
DemonAttackDeterministic-v0
DemonAttackDeterministic-v3
DemonAttackNoFrameskip-v0
DemonAttackNoFrameskip-v3
DoubleDunk-ram-v0
DoubleDunk-ram-v3
DoubleDunk-ramDeterministic-v0
DoubleDunk-ramDeterministic-v3
DoubleDunk-ramNoFrameskip-v0
DoubleDunk-ramNoFrameskip-v3
DoubleDunk-v0
DoubleDunk-v3
DoubleDunkDeterministic-v0
DoubleDunkDeterministic-v3
DoubleDunkNoFrameskip-v0
DoubleDunkNoFrameskip-v3
DuplicatedInput-v0
ElevatorAction-ram-v0
ElevatorAction-ram-v3
ElevatorAction-ramDeterministic-v0
ElevatorAction-ramDeterministic-v3
ElevatorAction-ramNoFrameskip-v0
ElevatorAction-ramNoFrameskip-v3
ElevatorAction-v0
ElevatorAction-v3
ElevatorActionDeterministic-v0
ElevatorActionDeterministic-v3
ElevatorActionNoFrameskip-v0
ElevatorActionNoFrameskip-v3
Enduro-ram-v0
Enduro-ram-v3
Enduro-ramDeterministic-v0
Enduro-ramDeterministic-v3
Enduro-ramNoFrameskip-v0
Enduro-ramNoFrameskip-v3
Enduro-v0
Enduro-v3
EnduroDeterministic-v0
EnduroDeterministic-v3
EnduroNoFrameskip-v0
EnduroNoFrameskip-v3
FishingDerby-ram-v0
FishingDerby-ram-v3
FishingDerby-ramDeterministic-v0
FishingDerby-ramDeterministic-v3
FishingDerby-ramNoFrameskip-v0
FishingDerby-ramNoFrameskip-v3
FishingDerby-v0
FishingDerby-v3
FishingDerbyDeterministic-v0
FishingDerbyDeterministic-v3
FishingDerbyNoFrameskip-v0
FishingDerbyNoFrameskip-v3
Freeway-ram-v0
Freeway-ram-v3
Freeway-ramDeterministic-v0
Freeway-ramDeterministic-v3
Freeway-ramNoFrameskip-v0
Freeway-ramNoFrameskip-v3
Freeway-v0
Freeway-v3
FreewayDeterministic-v0
FreewayDeterministic-v3
FreewayNoFrameskip-v0
FreewayNoFrameskip-v3
Frostbite-ram-v0
Frostbite-ram-v3
Frostbite-ramDeterministic-v0
Frostbite-ramDeterministic-v3
Frostbite-ramNoFrameskip-v0
Frostbite-ramNoFrameskip-v3
Frostbite-v0
Frostbite-v3
FrostbiteDeterministic-v0
FrostbiteDeterministic-v3
FrostbiteNoFrameskip-v0
FrostbiteNoFrameskip-v3
FrozenLake-v0
FrozenLake8x8-v0
Go19x19-v0
Go9x9-v0
Gopher-ram-v0
Gopher-ram-v3
Gopher-ramDeterministic-v0
Gopher-ramDeterministic-v3
Gopher-ramNoFrameskip-v0
Gopher-ramNoFrameskip-v3
Gopher-v0
Gopher-v3
GopherDeterministic-v0
GopherDeterministic-v3
GopherNoFrameskip-v0
GopherNoFrameskip-v3
Gravitar-ram-v0
Gravitar-ram-v3
Gravitar-ramDeterministic-v0
Gravitar-ramDeterministic-v3
Gravitar-ramNoFrameskip-v0
Gravitar-ramNoFrameskip-v3
Gravitar-v0
Gravitar-v3
GravitarDeterministic-v0
GravitarDeterministic-v3
GravitarNoFrameskip-v0
GravitarNoFrameskip-v3
GuessingGame-v0
HalfCheetah-v1
Hex9x9-v0
Hopper-v1
HotterColder-v0
Humanoid-v1
HumanoidStandup-v1
IceHockey-ram-v0
IceHockey-ram-v3
IceHockey-ramDeterministic-v0
IceHockey-ramDeterministic-v3
IceHockey-ramNoFrameskip-v0
IceHockey-ramNoFrameskip-v3
IceHockey-v0
IceHockey-v3
IceHockeyDeterministic-v0
IceHockeyDeterministic-v3
IceHockeyNoFrameskip-v0
IceHockeyNoFrameskip-v3
InvertedDoublePendulum-v1
InvertedPendulum-v1
Jamesbond-ram-v0
Jamesbond-ram-v3
Jamesbond-ramDeterministic-v0
Jamesbond-ramDeterministic-v3
Jamesbond-ramNoFrameskip-v0
Jamesbond-ramNoFrameskip-v3
Jamesbond-v0
Jamesbond-v3
JamesbondDeterministic-v0
JamesbondDeterministic-v3
JamesbondNoFrameskip-v0
JamesbondNoFrameskip-v3
JourneyEscape-ram-v0
JourneyEscape-ram-v3
JourneyEscape-ramDeterministic-v0
JourneyEscape-ramDeterministic-v3
JourneyEscape-ramNoFrameskip-v0
JourneyEscape-ramNoFrameskip-v3
JourneyEscape-v0
JourneyEscape-v3
JourneyEscapeDeterministic-v0
JourneyEscapeDeterministic-v3
JourneyEscapeNoFrameskip-v0
JourneyEscapeNoFrameskip-v3
Kangaroo-ram-v0
Kangaroo-ram-v3
Kangaroo-ramDeterministic-v0
Kangaroo-ramDeterministic-v3
Kangaroo-ramNoFrameskip-v0
Kangaroo-ramNoFrameskip-v3
Kangaroo-v0
Kangaroo-v3
KangarooDeterministic-v0
KangarooDeterministic-v3
KangarooNoFrameskip-v0
KangarooNoFrameskip-v3
Krull-ram-v0
Krull-ram-v3
Krull-ramDeterministic-v0
Krull-ramDeterministic-v3
Krull-ramNoFrameskip-v0
Krull-ramNoFrameskip-v3
Krull-v0
Krull-v3
KrullDeterministic-v0
KrullDeterministic-v3
KrullNoFrameskip-v0
KrullNoFrameskip-v3
KungFuMaster-ram-v0
KungFuMaster-ram-v3
KungFuMaster-ramDeterministic-v0
KungFuMaster-ramDeterministic-v3
KungFuMaster-ramNoFrameskip-v0
KungFuMaster-ramNoFrameskip-v3
KungFuMaster-v0
KungFuMaster-v3
KungFuMasterDeterministic-v0
KungFuMasterDeterministic-v3
KungFuMasterNoFrameskip-v0
KungFuMasterNoFrameskip-v3
LunarLander-v2
LunarLanderContinuous-v2
MontezumaRevenge-ram-v0
MontezumaRevenge-ram-v3
MontezumaRevenge-ramDeterministic-v0
MontezumaRevenge-ramDeterministic-v3
MontezumaRevenge-ramNoFrameskip-v0
MontezumaRevenge-ramNoFrameskip-v3
MontezumaRevenge-v0
MontezumaRevenge-v3
MontezumaRevengeDeterministic-v0
MontezumaRevengeDeterministic-v3
MontezumaRevengeNoFrameskip-v0
MontezumaRevengeNoFrameskip-v3
MountainCar-v0
MountainCarContinuous-v0
MsPacman-ram-v0
MsPacman-ram-v3
MsPacman-ramDeterministic-v0
MsPacman-ramDeterministic-v3
MsPacman-ramNoFrameskip-v0
MsPacman-ramNoFrameskip-v3
MsPacman-v0
MsPacman-v3
MsPacmanDeterministic-v0
MsPacmanDeterministic-v3
MsPacmanNoFrameskip-v0
MsPacmanNoFrameskip-v3
NChain-v0
NameThisGame-ram-v0
NameThisGame-ram-v3
NameThisGame-ramDeterministic-v0
NameThisGame-ramDeterministic-v3
NameThisGame-ramNoFrameskip-v0
NameThisGame-ramNoFrameskip-v3
NameThisGame-v0
NameThisGame-v3
NameThisGameDeterministic-v0
NameThisGameDeterministic-v3
NameThisGameNoFrameskip-v0
NameThisGameNoFrameskip-v3
OffSwitchCartpole-v0
OffSwitchCartpoleProb-v0
OneRoundDeterministicReward-v0
OneRoundNondeterministicReward-v0
Pendulum-v0
Phoenix-ram-v0
Phoenix-ram-v3
Phoenix-ramDeterministic-v0
Phoenix-ramDeterministic-v3
Phoenix-ramNoFrameskip-v0
Phoenix-ramNoFrameskip-v3
Phoenix-v0
Phoenix-v3
PhoenixDeterministic-v0
PhoenixDeterministic-v3
PhoenixNoFrameskip-v0
PhoenixNoFrameskip-v3
Pitfall-ram-v0
Pitfall-ram-v3
Pitfall-ramDeterministic-v0
Pitfall-ramDeterministic-v3
Pitfall-ramNoFrameskip-v0
Pitfall-ramNoFrameskip-v3
Pitfall-v0
Pitfall-v3
PitfallDeterministic-v0
PitfallDeterministic-v3
PitfallNoFrameskip-v0
PitfallNoFrameskip-v3
Pong-ram-v0
Pong-ram-v3
Pong-ramDeterministic-v0
Pong-ramDeterministic-v3
Pong-ramNoFrameskip-v0
Pong-ramNoFrameskip-v3
Pong-v0
Pong-v3
PongDeterministic-v0
PongDeterministic-v3
PongNoFrameskip-v0
PongNoFrameskip-v3
Pooyan-ram-v0
Pooyan-ram-v3
Pooyan-ramDeterministic-v0
Pooyan-ramDeterministic-v3
Pooyan-ramNoFrameskip-v0
Pooyan-ramNoFrameskip-v3
Pooyan-v0
Pooyan-v3
PooyanDeterministic-v0
PooyanDeterministic-v3
PooyanNoFrameskip-v0
PooyanNoFrameskip-v3
PredictActionsCartpole-v0
PredictObsCartpole-v0
PrivateEye-ram-v0
PrivateEye-ram-v3
PrivateEye-ramDeterministic-v0
PrivateEye-ramDeterministic-v3
PrivateEye-ramNoFrameskip-v0
PrivateEye-ramNoFrameskip-v3
PrivateEye-v0
PrivateEye-v3
PrivateEyeDeterministic-v0
PrivateEyeDeterministic-v3
PrivateEyeNoFrameskip-v0
PrivateEyeNoFrameskip-v3
Qbert-ram-v0
Qbert-ram-v3
Qbert-ramDeterministic-v0
Qbert-ramDeterministic-v3
Qbert-ramNoFrameskip-v0
Qbert-ramNoFrameskip-v3
Qbert-v0
Qbert-v3
QbertDeterministic-v0
QbertDeterministic-v3
QbertNoFrameskip-v0
QbertNoFrameskip-v3
Reacher-v1
RepeatCopy-v0
Reverse-v0
ReversedAddition-v0
ReversedAddition3-v0
Riverraid-ram-v0
Riverraid-ram-v3
Riverraid-ramDeterministic-v0
Riverraid-ramDeterministic-v3
Riverraid-ramNoFrameskip-v0
Riverraid-ramNoFrameskip-v3
Riverraid-v0
Riverraid-v3
RiverraidDeterministic-v0
RiverraidDeterministic-v3
RiverraidNoFrameskip-v0
RiverraidNoFrameskip-v3
RoadRunner-ram-v0
RoadRunner-ram-v3
RoadRunner-ramDeterministic-v0
RoadRunner-ramDeterministic-v3
RoadRunner-ramNoFrameskip-v0
RoadRunner-ramNoFrameskip-v3
RoadRunner-v0
RoadRunner-v3
RoadRunnerDeterministic-v0
RoadRunnerDeterministic-v3
RoadRunnerNoFrameskip-v0
RoadRunnerNoFrameskip-v3
Robotank-ram-v0
Robotank-ram-v3
Robotank-ramDeterministic-v0
Robotank-ramDeterministic-v3
Robotank-ramNoFrameskip-v0
Robotank-ramNoFrameskip-v3
Robotank-v0
Robotank-v3
RobotankDeterministic-v0
RobotankDeterministic-v3
RobotankNoFrameskip-v0
RobotankNoFrameskip-v3
Roulette-v0
Seaquest-ram-v0
Seaquest-ram-v3
Seaquest-ramDeterministic-v0
Seaquest-ramDeterministic-v3
Seaquest-ramNoFrameskip-v0
Seaquest-ramNoFrameskip-v3
Seaquest-v0
Seaquest-v3
SeaquestDeterministic-v0
SeaquestDeterministic-v3
SeaquestNoFrameskip-v0
SeaquestNoFrameskip-v3
SemisuperPendulumDecay-v0
SemisuperPendulumNoise-v0
SemisuperPendulumRandom-v0
Skiing-ram-v0
Skiing-ram-v3
Skiing-ramDeterministic-v0
Skiing-ramDeterministic-v3
Skiing-ramNoFrameskip-v0
Skiing-ramNoFrameskip-v3
Skiing-v0
Skiing-v3
SkiingDeterministic-v0
SkiingDeterministic-v3
SkiingNoFrameskip-v0
SkiingNoFrameskip-v3
Solaris-ram-v0
Solaris-ram-v3
Solaris-ramDeterministic-v0
Solaris-ramDeterministic-v3
Solaris-ramNoFrameskip-v0
Solaris-ramNoFrameskip-v3
Solaris-v0
Solaris-v3
SolarisDeterministic-v0
SolarisDeterministic-v3
SolarisNoFrameskip-v0
SolarisNoFrameskip-v3
SpaceInvaders-ram-v0
SpaceInvaders-ram-v3
SpaceInvaders-ramDeterministic-v0
SpaceInvaders-ramDeterministic-v3
SpaceInvaders-ramNoFrameskip-v0
SpaceInvaders-ramNoFrameskip-v3
SpaceInvaders-v0
SpaceInvaders-v3
SpaceInvadersDeterministic-v0
SpaceInvadersDeterministic-v3
SpaceInvadersNoFrameskip-v0
SpaceInvadersNoFrameskip-v3
StarGunner-ram-v0
StarGunner-ram-v3
StarGunner-ramDeterministic-v0
StarGunner-ramDeterministic-v3
StarGunner-ramNoFrameskip-v0
StarGunner-ramNoFrameskip-v3
StarGunner-v0
StarGunner-v3
StarGunnerDeterministic-v0
StarGunnerDeterministic-v3
StarGunnerNoFrameskip-v0
StarGunnerNoFrameskip-v3
Swimmer-v1
Taxi-v2
Tennis-ram-v0
Tennis-ram-v3
Tennis-ramDeterministic-v0
Tennis-ramDeterministic-v3
Tennis-ramNoFrameskip-v0
Tennis-ramNoFrameskip-v3
Tennis-v0
Tennis-v3
TennisDeterministic-v0
TennisDeterministic-v3
TennisNoFrameskip-v0
TennisNoFrameskip-v3
TimePilot-ram-v0
TimePilot-ram-v3
TimePilot-ramDeterministic-v0
TimePilot-ramDeterministic-v3
TimePilot-ramNoFrameskip-v0
TimePilot-ramNoFrameskip-v3
TimePilot-v0
TimePilot-v3
TimePilotDeterministic-v0
TimePilotDeterministic-v3
TimePilotNoFrameskip-v0
TimePilotNoFrameskip-v3
Tutankham-ram-v0
Tutankham-ram-v3
Tutankham-ramDeterministic-v0
Tutankham-ramDeterministic-v3
Tutankham-ramNoFrameskip-v0
Tutankham-ramNoFrameskip-v3
Tutankham-v0
Tutankham-v3
TutankhamDeterministic-v0
TutankhamDeterministic-v3
TutankhamNoFrameskip-v0
TutankhamNoFrameskip-v3
TwoRoundDeterministicReward-v0
TwoRoundNondeterministicReward-v0
UpNDown-ram-v0
UpNDown-ram-v3
UpNDown-ramDeterministic-v0
UpNDown-ramDeterministic-v3
UpNDown-ramNoFrameskip-v0
UpNDown-ramNoFrameskip-v3
UpNDown-v0
UpNDown-v3
UpNDownDeterministic-v0
UpNDownDeterministic-v3
UpNDownNoFrameskip-v0
UpNDownNoFrameskip-v3
Venture-ram-v0
Venture-ram-v3
Venture-ramDeterministic-v0
Venture-ramDeterministic-v3
Venture-ramNoFrameskip-v0
Venture-ramNoFrameskip-v3
Venture-v0
Venture-v3
VentureDeterministic-v0
VentureDeterministic-v3
VentureNoFrameskip-v0
VentureNoFrameskip-v3
VideoPinball-ram-v0
VideoPinball-ram-v3
VideoPinball-ramDeterministic-v0
VideoPinball-ramDeterministic-v3
VideoPinball-ramNoFrameskip-v0
VideoPinball-ramNoFrameskip-v3
VideoPinball-v0
VideoPinball-v3
VideoPinballDeterministic-v0
VideoPinballDeterministic-v3
VideoPinballNoFrameskip-v0
VideoPinballNoFrameskip-v3
Walker2d-v1
WizardOfWor-ram-v0
WizardOfWor-ram-v3
WizardOfWor-ramDeterministic-v0
WizardOfWor-ramDeterministic-v3
WizardOfWor-ramNoFrameskip-v0
WizardOfWor-ramNoFrameskip-v3
WizardOfWor-v0
WizardOfWor-v3
WizardOfWorDeterministic-v0
WizardOfWorDeterministic-v3
WizardOfWorNoFrameskip-v0
WizardOfWorNoFrameskip-v3
YarsRevenge-ram-v0
YarsRevenge-ram-v3
YarsRevenge-ramDeterministic-v0
YarsRevenge-ramDeterministic-v3
YarsRevenge-ramNoFrameskip-v0
YarsRevenge-ramNoFrameskip-v3
YarsRevenge-v0
YarsRevenge-v3
YarsRevengeDeterministic-v0
YarsRevengeDeterministic-v3
YarsRevengeNoFrameskip-v0
YarsRevengeNoFrameskip-v3
Zaxxon-ram-v0
Zaxxon-ram-v3
Zaxxon-ramDeterministic-v0
Zaxxon-ramDeterministic-v3
Zaxxon-ramNoFrameskip-v0
Zaxxon-ramNoFrameskip-v3
Zaxxon-v0
Zaxxon-v3
ZaxxonDeterministic-v0
ZaxxonDeterministic-v3
ZaxxonNoFrameskip-v0
ZaxxonNoFrameskip-v3
"""